<?xml version="1.0" encoding="utf-8"?><Database Name="FoodShop" Class="FoodShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\FoodShop.mdf;Integrated Security=True" SettingsObjectName="VisualBasicAssignment.My.MySettings" SettingsPropertyName="FoodShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="birthday_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="membership_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="wallate_amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="User_Customer" Member="User" ThisKey="user_id" OtherKey="user_id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_role" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="phone_num" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Customer" Member="Customer" ThisKey="user_id" OtherKey="user_id" Type="Customer" Cardinality="One" />
      <Association Name="User_Staff" Member="Staff" ThisKey="user_id" OtherKey="user_id" Type="Staff" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="position_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salary" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="User_Staff" Member="User" ThisKey="user_id" OtherKey="user_id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>