// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class Address
    {
        public Guid id { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string details { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string poscode { get; set; }
        public string country { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; } = new HashSet<Delivery>();
        public virtual ICollection<Delivery> Deliveries1 { get; set; } = new HashSet<Delivery>();
        public virtual ICollection<DeliveryChain> DeliveryChains { get; set; } = new HashSet<DeliveryChain>();
        public virtual ICollection<User> Users { get; set; } = new HashSet<User>();
    }
}