'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property id As System.Guid
    Public Property latitude As Double
    Public Property longitude As Double
    Public Property details As String
    Public Property street As String
    Public Property city As String
    Public Property state As String
    Public Property poscode As String
    Public Property country As String

    Public Overridable Property Deliveries As ICollection(Of Delivery) = New HashSet(Of Delivery)
    Public Overridable Property Deliveries1 As ICollection(Of Delivery) = New HashSet(Of Delivery)
    Public Overridable Property DeliveryChains As ICollection(Of DeliveryChain) = New HashSet(Of DeliveryChain)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
