// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace VisualBasicAssignment
{
    public partial class CartDetail
    {
        public int cart_id { get; set; }
        public int food_id { get; set; }
        public int quantity { get; set; }
        public DateTime add_datetime { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual Food Food { get; set; }
    }
}