// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class Cart
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string remark { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CartDetail> CartDetails { get; set; } = new HashSet<CartDetail>();
    }
}