'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property user_id As Integer
    Public Property birthday_date As Nullable(Of Date)
    Public Property membership_id As Integer
    Public Property wallate_amount As Nullable(Of Double)

    Public Overridable Property Membership As Membership
    Public Overridable Property User As User

End Class
