// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace VisualBasicAssignment
{
    public partial class Customer
    {
        public int user_id { get; set; }
        public DateTime? birthday_date { get; set; }
        public int membership_id { get; set; }
        public double? wallate_amount { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual User User { get; set; }
    }
}