'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeliveryChain
    Public Property id As System.Guid
    Public Property arrival_dates As Date
    Public Property address_id As System.Guid
    Public Property delivery_status As Nullable(Of System.Guid)
    Public Property notes As String

    Public Overridable Property Address As Address
    Public Overridable Property DeliveryStatu As DeliveryStatu
    Public Overridable Property Deliveries As ICollection(Of Delivery) = New HashSet(Of Delivery)

End Class
