// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class Delivery
    {
        public Guid id { get; set; }
        public Guid source { get; set; }
        public Guid destination { get; set; }
        public string delivery_note { get; set; }
        public Guid final_delivery_status { get; set; }
        public Guid delivery_company { get; set; }
        public DateTime? recive_dates { get; set; }
        public byte[] recive_prove { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual DeliveryCompany DeliveryCompany { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual ICollection<DeliveryChain> DeliveryChains { get; set; } = new HashSet<DeliveryChain>();
    }
}