// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class DeliveryCompany
    {
        public Guid id { get; set; }
        public string company_name { get; set; }
        public string company_phones { get; set; }
        public string description { get; set; }
        public double rm_per_g { get; set; }
        public double rm_per_cm3 { get; set; }
        public double gradient { get; set; }
        public string prefence_country { get; set; }
        public bool oversea_support { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; } = new HashSet<Delivery>();
    }
}