'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Delivery
    Public Property id As System.Guid
    Public Property source As System.Guid
    Public Property destination As System.Guid
    Public Property delivery_note As String
    Public Property final_delivery_status As System.Guid
    Public Property delivery_company As System.Guid
    Public Property recive_dates As Nullable(Of Date)
    Public Property recive_prove As Byte()

    Public Overridable Property Address As Address
    Public Overridable Property Address1 As Address
    Public Overridable Property DeliveryCompany As DeliveryCompany
    Public Overridable Property DeliveryStatu As DeliveryStatu
    Public Overridable Property DeliveryChains As ICollection(Of DeliveryChain) = New HashSet(Of DeliveryChain)

End Class
