// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class DeliveryChain
    {
        public Guid id { get; set; }
        public DateTime arrival_dates { get; set; }
        public Guid address_id { get; set; }
        public Guid? delivery_status { get; set; }
        public string notes { get; set; }
        public virtual Address Address { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; } = new HashSet<Delivery>();
    }
}