'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeliveryStatu
    Public Property id As System.Guid
    Public Property name As String
    Public Property description As String

    Public Overridable Property Deliveries As ICollection(Of Delivery) = New HashSet(Of Delivery)
    Public Overridable Property DeliveryChains As ICollection(Of DeliveryChain) = New HashSet(Of DeliveryChain)

End Class
