'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeliveryCompany
    Public Property id As System.Guid
    Public Property company_name As String
    Public Property company_phones As String
    Public Property description As String
    Public Property rm_per_g As Double
    Public Property rm_per_cm3 As Double
    Public Property gradient As Double
    Public Property prefence_country As String
    Public Property oversea_support As Boolean

    Public Overridable Property Deliveries As ICollection(Of Delivery) = New HashSet(Of Delivery)

End Class
