// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class Food
    {
        public int id { get; set; }
        public int duty_staff_id { get; set; }
        public byte[] image { get; set; }
        public double price { get; set; }
        public int stock { get; set; }
        public DateTime add_date { get; set; }
        public string title { get; set; }
        public string descriptions { get; set; }
        public string poscode { get; set; }
        public int? catergory_id { get; set; }
        public virtual ICollection<CartDetail> CartDetails { get; set; } = new HashSet<CartDetail>();
        public virtual Catergory Catergory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new HashSet<OrderDetail>();
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new HashSet<PaymentDetail>();
    }
}