'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Food
    Public Property id As Integer
    Public Property duty_staff_id As Integer
    Public Property image As Byte()
    Public Property price As Double
    Public Property stock As Integer
    Public Property add_date As Date
    Public Property title As String
    Public Property descriptions As String
    Public Property poscode As String
    Public Property catergory_id As Nullable(Of Integer)

    Public Overridable Property CartDetails As ICollection(Of CartDetail) = New HashSet(Of CartDetail)
    Public Overridable Property Catergory As Catergory
    Public Overridable Property User As User
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)
    Public Overridable Property PaymentDetails As ICollection(Of PaymentDetail) = New HashSet(Of PaymentDetail)

End Class
