'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FoodShopEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FoodShopEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property Carts() As DbSet(Of Cart)
    Public Overridable Property CartDetails() As DbSet(Of CartDetail)
    Public Overridable Property Catergories() As DbSet(Of Catergory)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Deliveries() As DbSet(Of Delivery)
    Public Overridable Property DeliveryChains() As DbSet(Of DeliveryChain)
    Public Overridable Property DeliveryCompanies() As DbSet(Of DeliveryCompany)
    Public Overridable Property DeliveryStatus() As DbSet(Of DeliveryStatu)
    Public Overridable Property Foods() As DbSet(Of Food)
    Public Overridable Property Memberships() As DbSet(Of Membership)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property OrderDetails() As DbSet(Of OrderDetail)
    Public Overridable Property Payments() As DbSet(Of Payment)
    Public Overridable Property PaymentDetails() As DbSet(Of PaymentDetail)
    Public Overridable Property PaymentMethods() As DbSet(Of PaymentMethod)
    Public Overridable Property PaymentStatus() As DbSet(Of PaymentStatu)
    Public Overridable Property Positions() As DbSet(Of Position)
    Public Overridable Property ResetPasswordTokens() As DbSet(Of ResetPasswordToken)
    Public Overridable Property Staffs() As DbSet(Of Staff)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property PaymentDetailsReportViews() As DbSet(Of PaymentDetailsReportView)

End Class
