'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property id As Integer
    Public Property customer_id As Integer
    Public Property order_status As String
    Public Property datetime As Nullable(Of Date)
    Public Property customer_note As String
    Public Property payload As String

    Public Overridable Property User As User
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)

End Class
