'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderDetail
    Public Property order_id As Integer
    Public Property food_id As Integer
    Public Property quantity As Integer
    Public Property add_datetime As Date

    Public Overridable Property Food As Food
    Public Overridable Property Order As Order

End Class
