'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Payment
    Public Property id As System.Guid
    Public Property payment_method As System.Guid
    Public Property payment_status As System.Guid
    Public Property user_id As Integer
    Public Property tax_change As Nullable(Of Double)
    Public Property net_pay As Nullable(Of Double)
    Public Property discount As Nullable(Of Double)
    Public Property total_pay As Nullable(Of Double)
    Public Property customer_paid As Nullable(Of Double)
    Public Property payment_date As Nullable(Of Date)
    Public Property payment_meta As String
    Public Property notes As String

    Public Overridable Property PaymentMethod As PaymentMethod
    Public Overridable Property PaymentStatu As PaymentStatu
    Public Overridable Property User As User
    Public Overridable Property PaymentDetails As ICollection(Of PaymentDetail) = New HashSet(Of PaymentDetail)

End Class
