'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentDetail
    Public Property payment_id As System.Guid
    Public Property food_id As Integer
    Public Property quantity As Nullable(Of Integer)
    Public Property add_date As Nullable(Of Date)

    Public Overridable Property Food As Food
    Public Overridable Property Payment As Payment

End Class
