'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentStatu
    Public Property id As System.Guid
    Public Property name As String
    Public Property description As String

    Public Overridable Property Payments As ICollection(Of Payment) = New HashSet(Of Payment)

End Class
