// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class Payment
    {
        public Guid id { get; set; }
        public Guid payment_method { get; set; }
        public Guid payment_status { get; set; }
        public int user_id { get; set; }
        public double? tax_change { get; set; }
        public double? net_pay { get; set; }
        public double? discount { get; set; }
        public double? total_pay { get; set; }
        public double? customer_paid { get; set; }
        public DateTime? payment_date { get; set; }
        public string payment_meta { get; set; }
        public string notes { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new HashSet<PaymentDetail>();
    }
}