'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentDetailsReportView
    Public Property payment_id As System.Guid
    Public Property total_pay As Nullable(Of Double)
    Public Property net_pay As Nullable(Of Double)
    Public Property discount As Nullable(Of Double)
    Public Property payment_status As System.Guid
    Public Property payment_method As System.Guid
    Public Property tax_change As Nullable(Of Double)
    Public Property food_id As Integer
    Public Property quantity As Nullable(Of Integer)
    Public Property price As Double
    Public Property descriptions As String
    Public Property stock As Integer
    Public Property title As String
    Public Property payment_status_name As String
    Public Property payment_method_name As String
    Public Property payment_date As Nullable(Of Date)

End Class
