// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace VisualBasicAssignment
{
    public partial class PaymentDetail
    {
        public Guid payment_id { get; set; }
        public int food_id { get; set; }
        public int? quantity { get; set; }
        public DateTime? add_date { get; set; }
        public virtual Food Food { get; set; }
        public virtual Payment Payment { get; set; }
    }
}