// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace VisualBasicAssignment
{
    public partial class PaymentDetailsReportView
    {
        public Guid payment_id { get; set; }
        public double? total_pay { get; set; }
        public double? net_pay { get; set; }
        public double? discount { get; set; }
        public Guid payment_status { get; set; }
        public Guid payment_method { get; set; }
        public double? tax_change { get; set; }
        public int food_id { get; set; }
        public int? quantity { get; set; }
        public double price { get; set; }
        public string descriptions { get; set; }
        public int stock { get; set; }
        public string title { get; set; }
        public string payment_status_name { get; set; }
        public string payment_method_name { get; set; }
        public DateTime? payment_date { get; set; }
    }
}