'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ResetPasswordToken
    Public Property id As Integer
    Public Property key As String
    Public Property exp_date As Nullable(Of Date)
    Public Property user_id As Integer

    Public Overridable Property User As User

End Class
