'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Staff
    Public Property user_id As Integer
    Public Property priority As Integer
    Public Property position_id As Integer
    Public Property salary As Nullable(Of Double)

    Public Overridable Property Position As Position
    Public Overridable Property User As User

End Class
