// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


namespace VisualBasicAssignment
{
    public partial class Staff
    {
        public int user_id { get; set; }
        public int priority { get; set; }
        public int position_id { get; set; }
        public double? salary { get; set; }
        public virtual Position Position { get; set; }
        public virtual User User { get; set; }
    }
}