// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.
// 
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace VisualBasicAssignment
{
    public partial class User
    {
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string username { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string user_role { get; set; }
        public string phone_num { get; set; }
        public string gender { get; set; }
        public byte[] picture { get; set; }
        public string password { get; set; }
        public virtual ICollection<Cart> Carts { get; set; } = new HashSet<Cart>();
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Food> Foods { get; set; } = new HashSet<Food>();
        public virtual ICollection<Order> Orders { get; set; } = new HashSet<Order>();
        public virtual ICollection<Payment> Payments { get; set; } = new HashSet<Payment>();
        public virtual ICollection<ResetPasswordToken> ResetPasswordTokens { get; set; } = new HashSet<ResetPasswordToken>();
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Address> Addresses { get; set; } = new HashSet<Address>();
    }
}